services:
  - type: web
    name: plantakeoff-backend
    env: node
    region: oregon
    plan: starter
    rootDir: backend
    buildCommand: export NODE_OPTIONS="--max-old-space-size=2048" && npm install --include=dev && npx prisma generate && npm run build
    startCommand: node --max-old-space-size=1024 dist/main.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: plantakeoff-backend
          property: port
      - key: NODE_OPTIONS
        value: "--max-old-space-size=1024"

