[phases.setup]
nixPkgs = [
  "nodejs_20",
  "npm-10_x", 
  "python3",
  "postgresql",
  "vips",
  "imagemagick",
  "graphicsmagick",
  "ghostscript",
  "poppler_utils",
  "cairo",
  "pango",
  "pixman"
]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = [
  "npx prisma generate",
  "npm run build"
]

[phases.deploy]
cmds = [
  "npx prisma migrate deploy"
]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"

MINIMAL_START='false'
