[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x", "python3", "postgresql", "vips", "imagemagick", "graphicsmagick", "ghostscript"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = [
  "npx prisma generate",
  "npm run build"
]

[start]
cmd = "npm run start:resilient"

[variables]
NODE_ENV = "production"

MINIMAL_START='false'
