[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x", "python3", "postgresql", "vips"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = [
  "npm run build",
  "npx prisma generate",
  "npx prisma migrate deploy"
]

[start]
cmd = "npm run start:prod"

[variables]
NODE_ENV = "production"
MINIMAL_START = "false"